---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: terminalboard-ci
- name: terminalboard
  path: gopath/src/github.com/pivotal-cf/terminalboard

run:
  path: terminalboard-ci/tasks/terminalboard-test/task

params:
  TERMINALBOARD_DIR: gopath/src/github.com/pivotal-cf/terminalboard
